apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.env.MYSQL_ROOT_PASSWORD }}
        - name: MYSQL_DB
          value: {{ .Values.env.MYSQL_DB }}
        volumeMounts:
        - name: mysql-init-sql
          mountPath: /docker-entrypoint-initdb.d
        - name: mysqldata
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-init-sql
        configMap:
          name: mysql-init-sql
      - name: mysqldata
        persistentVolumeClaim:
          claimName: mysql-pvc
