# values.yaml

name: app
image: 339713101508.dkr.ecr.ap-south-1.amazonaws.com/two-tier:${BUILD_NUMBER}
mysql:
  host: mysql
  user: root
  password: admin
  db: mydb
port: 5000
replicas: 1


service:
  protocol: TCP
  targetPort: 5000
  port: 80
  nodePort: 30004
  type: LoadBalancer