apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image }}"
        ports:
        - containerPort: {{.Values.port}}
        env:
          - name: MYSQL_HOST
            value: {{ .Values.mysql.host }}
          - name: MYSQL_USER
            value: {{ .Values.mysql.user }}
          - name: MYSQL_PASSWORD
            value: {{ .Values.mysql.password }}
          - name: MYSQL_DB
            value: {{ .Values.mysql.db }}
        imagePullPolicy: Always
