apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app
spec:
  containers:
    - name: two-tier-app
      image: app30/app:latest
      env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_DB
          value: "mydb"
      ports:
        - containerPort: 5000
      imagePullPolicy: always
  
